### ISSUE TITLE
Manual de usuario

### ISSUE THREAD

**Issue by Wissenss** [Wissenss/AccessControl#9]
Uno de los requerimientos de la rubrica es agregar instrucciones/requerimientos para compilar

**Comment by Bistraw** [comment]
- [x] **Portada**: La portada del manual de usuario debe incluir el título del manual, el logotipo o nombre de la empresa, la versión del producto, el número de serie o identificador, y posiblemente la fecha de publicación.
- [x] **Índice**: El índice es una lista de los diferentes apartados, secciones o temas que se tratarán en el manual, junto con las páginas correspondientes. Esto ayuda a los usuarios a encontrar rápidamente la información que necesitan
- [x] **Introducción**: La introducción proporciona una visión general del producto o servicio y su propósito. También puede incluir una descripción de las características clave, las ventajas y cómo utilizar el manual.
- [ ] **Instalación y configuración**: Esta sección detalla los pasos necesarios para instalar y configurar el producto o servicio. Puede incluir requisitos de hardware y software, instrucciones para conectar dispositivos, configuración de opciones y ajustes iniciales.
- [ ] **Guia rapida de Inicio**: En esta sección se proporciona una guía breve y concisa para que los usuarios puedan comenzar a utilizar rápidamente el producto o servicio. Se pueden incluir instrucciones básicas, configuraciones predeterminadas y ejemplos simples.
- [ ] **uso basico**: Aquí se explica cómo utilizar las funcionalidades básicas del producto o servicio. Se describen las operaciones esenciales y se proporcionan instrucciones paso a paso para realizar tareas comunes
- [ ] Funciones: Esta sección aborda características más avanzadas del producto o servicio. Se proporcionan instrucciones detalladas, ejemplos y consejos sobre cómo aprovechar al máximo las funcionalidades adicionales.
- [ ] **Solucion de problemas**:  En esta parte se incluyen consejos y soluciones para los problemas más comunes que los usuarios pueden encontrar al utilizar el producto o servicio. Se proporcionan descripciones de los problemas, posibles causas y las soluciones recomendadas.
- [ ] **Mantenimiento y cuidado**: Aquí se detallan las recomendaciones para el mantenimiento y cuidado adecuado del producto o servicio. Se incluyen instrucciones de limpieza, precauciones de seguridad y consejos para prolongar la vida útil del producto.
- [ ] **FAQ**: Se pueden incluir una lista de preguntas frecuentes y sus respuestas correspondientes. Esto puede ayudar a los usuarios a encontrar rápidamente soluciones a sus dudas comunes.
- [ ] **Glosario**: Si el producto o servicio utiliza terminología técnica o específica, se puede incluir un glosario con las definiciones de los términos clave.
- [x] **Informacion de contacto**: En la última sección, se debe proporcionar la información de contacto de soporte técnico o servicio al cliente. Esto puede incluir números de teléfono, direcciones de correo electrónico, enlaces a sitios web y otros canales de comunicación.

**Comment by Bistraw** [comment]
Nota: el indice se va actualiando
